name: Lint
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  checks:
    name: "Linter"
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Go"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: "Check out code"
        uses: actions/checkout@v3

      - name: "GolangCI-Lint"
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.50